[package]
name = "http-rest-file"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.9"
regex = "1.7.3"

[dev-dependencies]
pretty_assertions = "1.3.0"
