[package]
name = "http-rest-file"
version = "0.5.1"
edition = "2021"
authors = ["laeri@laeri.me"]
readme = "README.md"
repository = "https://github.com/Laeri/http-rest-file"
homepage = "https://github.com/Laeri/http-rest-file"
license = "MIT"
keywords = ["http", "parser", "jetbrains"]
categories = ["parser-implementations", "parsing"]
publish = true
description = "Parse jetbrains .http/.rest http client formatted files into a model or serialize an existing model to a file"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json"]
specta = ["dep:specta"]

[dependencies]
http = "1.4"
regex = "1.11"
serde_json = { version = "1.0.140", optional = true }
serde = { version = "1.0.220", features = ["derive"], optional = true }
specta = { version = "1.0.5", optional = true }
url = "2.5"
thiserror = "2.0"
lazy_static = "1.5"


[dev-dependencies]
pretty_assertions = "1.4"
